[Appearance]
color_scheme_path=
custom_palette=false
icon_theme=AdwaitaLegacy
standard_dialogs=default
style=kvantum-dark

[Fonts]
fixed="Noto Sans Mono,10,-1,5,50,0,0,0,0,0,Regular"
general="Noto Sans,10,-1,5,50,0,0,0,0,0,Regular"
